### ISSUE TITLE
Cannot run the code

### ISSUE THREAD

**Issue by ghost** [bernovie/political-polarization#1]
Thanks for your work! I cannot run the code, because the error `"from .pdtb_relations import PDTB_COLUMNS, COLUMN_LABELS
ImportError: attempted relative import with no known parent package"` in utils.py. 
Can you help me? Thank you very much!

**Comment by jjessyli** [comment]
Hello, the PDTB features are not used in the code -- feel free to comment out relevant components in utils.py (I believe this involves the function `process_data` which was eventually commented out).

**Comment by ghost** [comment]
Thanks! The code is working!
